spring:
  application:
    name: learnSpringMongoDb
  mongodb:
    uri: mongodb://admin:password@localhost:27017/ecommerce_db?authSource=admin
    auto-index-creation: true

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: INFO
    org.mongodb.driver: WARN